name: Publish

on:
  push:
    branches:
      - v3
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true
      - name: Build pages
        run: |
          bash make.sh
      - name: Publish pages
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          bash update_gh-pages.sh
